# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

before_script:
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# Supported node versions can be found here:
# https://github.com/nodejs/LTS#lts_schedule
# jest does not support node < 4
# https://facebook.github.io/jest/docs/troubleshooting.html#compatibility-issues
docs:build:
  script:
	- npm run docs:build
